sudo: false
language: node_js
node_js:
  - "7"
  - "6"
matrix:
  allow_failures:
    - node_js: "7"

before_install:
  - npm install --global yarn
install:
  - yarn install --frozen-lockfile

script:
  # Set up GraphQL assertions
  - export ASSERT_CONTRACTS="true"
  # Run our tests
  - yarn test

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
